// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga.modifier;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import slimeknights.tconstruct.library.modifiers.Modifier;
import slimeknights.tconstruct.library.modifiers.ModifierId;
import slimeknights.tconstruct.library.modifiers.ModifierManager;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

/**
 * Registry for TAIGA custom modifiers — ports of the 38 {@code TraitXxx} classes
 * from 1.12.2 TAIGA. Uses the same queue-and-drain pattern as
 * {@code com.soul.soa_additions.tconstructevo.TConEvoModifiers} since TC3's
 * modifier registry is not a Forge registry.
 *
 * <p>Modifier static fields are populated by {@link TaigaTraitList}.</p>
 */
public final class TaigaModifiers {

    private static final List<Holder<?>> PENDING = new ArrayList<>();

    private TaigaModifiers() {}

    public static <M extends Modifier> Holder<M> register(String name, Supplier<M> factory) {
        Holder<M> holder = new Holder<>(new ResourceLocation("taiga", name), factory);
        PENDING.add(holder);
        return holder;
    }

    public static void register(IEventBus modEventBus) {
        TaigaTraitList.bootstrap();
        modEventBus.addListener(TaigaModifiers::onModifierRegistration);
    }

    private static void onModifierRegistration(ModifierManager.ModifierRegistrationEvent event) {
        for (Holder<?> holder : PENDING) {
            holder.bindAndRegister(event);
        }
    }

    public static final class Holder<M extends Modifier> implements Supplier<M> {
        private final ResourceLocation id;
        private final Supplier<M> factory;
        private M instance;

        private Holder(ResourceLocation id, Supplier<M> factory) {
            this.id = id;
            this.factory = factory;
        }

        public ResourceLocation getId() { return id; }

        @Override public M get() {
            if (instance == null) {
                throw new IllegalStateException(
                        "Modifier " + id + " accessed before ModifierRegistrationEvent fired");
            }
            return instance;
        }

        @SuppressWarnings("unchecked")
        private void bindAndRegister(ModifierManager.ModifierRegistrationEvent event) {
            instance = factory.get();
            event.registerStatic(new ModifierId(id), instance);
        }
    }
}
