modLoader="javafml"
loaderVersion="1.20.1"
license="MIT"

[[mods]]
modId="soa_additions"
version="1.0.0"
displayName="Soul of Avarice Additions"
authors="Soul"
description='''Additions and tweaks for the Soul of Avarice modpack.'''

[[dependencies.soa_additions]]
modId="forge"
mandatory=true
versionRange="[43.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.soa_additions]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
