// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga;

import com.soul.soa_additions.taiga.event.TaigaTraitEvents;
import com.soul.soa_additions.taiga.modifier.TaigaModifiers;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.IEventBus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Bootstrap entry point for TAIGA content — a 1.20.1 Java port of the 1.12.2
 * TAIGA mod. Hard-depends on Tinkers' Construct 3.x for its material system,
 * molten-fluid block, and modifier API. Called from {@link com.soul.soa_additions.SoaAdditions}
 * only when {@code tconstruct} is present.
 */
public final class TaigaPlugin {

    public static final String MODID = "taiga";
    public static final Logger LOG = LoggerFactory.getLogger("soa_additions/taiga");

    private TaigaPlugin() {}

    public static void init(IEventBus modEventBus) {
        LOG.info("Tinkers' Construct detected — initialising TAIGA content");

        TaigaFluids.register(modEventBus);
        TaigaBlocks.register(modEventBus);
        TaigaItems.register(modEventBus);
        TaigaCreativeTab.register(modEventBus);

        TaigaModifiers.register(modEventBus);
        MinecraftForge.EVENT_BUS.register(TaigaTraitEvents.class);

        LOG.info("TAIGA content registered");
    }
}
