// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.material.FlowingFluid;
import net.minecraft.world.level.material.Fluid;
import net.minecraftforge.client.extensions.common.IClientFluidTypeExtensions;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fluids.FluidType;
import net.minecraftforge.fluids.ForgeFlowingFluid;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

public final class TaigaFluids {

    public static final DeferredRegister<Fluid> FLUIDS =
            DeferredRegister.create(ForgeRegistries.FLUIDS, TaigaPlugin.MODID);
    public static final DeferredRegister<FluidType> FLUID_TYPES =
            DeferredRegister.create(ForgeRegistries.Keys.FLUID_TYPES, TaigaPlugin.MODID);

    public static final Map<String, RegistryObject<FluidType>> TYPES = new HashMap<>();
    public static final Map<String, RegistryObject<FlowingFluid>> SOURCES = new HashMap<>();
    public static final Map<String, RegistryObject<FlowingFluid>> FLOWINGS = new HashMap<>();

    private static final ResourceLocation STILL_TEX = new ResourceLocation("tconstruct", "fluid/molten/still");
    private static final ResourceLocation FLOWING_TEX = new ResourceLocation("tconstruct", "fluid/molten/flowing");

    private TaigaFluids() {}

    private static RegistryObject<FluidType> regType(String name, int argb, int temp, int density, int viscosity, int luminosity) {
        return FLUID_TYPES.register(name, () -> new FluidType(FluidType.Properties.create()
                .density(density).viscosity(viscosity).temperature(temp).lightLevel(luminosity)
                .canPushEntity(true).canSwim(false).canDrown(false).canExtinguish(false)
                .canHydrate(false).canConvertToSource(false).supportsBoating(false)
                .sound(net.minecraftforge.common.SoundActions.BUCKET_FILL, SoundEvents.BUCKET_FILL_LAVA)
                .sound(net.minecraftforge.common.SoundActions.BUCKET_EMPTY, SoundEvents.BUCKET_EMPTY_LAVA)) {
            @Override
            public void initializeClient(Consumer<IClientFluidTypeExtensions> consumer) {
                consumer.accept(new IClientFluidTypeExtensions() {
                    @Override public ResourceLocation getStillTexture() { return STILL_TEX; }
                    @Override public ResourceLocation getFlowingTexture() { return FLOWING_TEX; }
                    @Override public int getTintColor() { return argb; }
                });
            }
        });
    }

    private static ForgeFlowingFluid.Properties props(String name) {
        return new ForgeFlowingFluid.Properties(
                () -> TYPES.get(name).get(),
                () -> SOURCES.get(name).get(),
                () -> FLOWINGS.get(name).get())
                .slopeFindDistance(2)
                .levelDecreasePerBlock(2)
                .tickRate(30)
                .block(() -> (LiquidBlock) TaigaBlocks.FLUID_BLOCKS.get(name).get())
                .bucket(() -> TaigaItems.BUCKETS.get(name).get());
    }

    static {
        TYPES.put("basalt", regType("basalt", 0xFFE4DDC3, 550, 2000, 6000, 10));
        TYPES.put("tiberium", regType("tiberium", 0xFFD4FF00, 400, 2000, 8000, 10));
        TYPES.put("aurorium", regType("aurorium", 0xFFEFAE94, 750, 2000, 10000, 10));
        TYPES.put("prometheum", regType("prometheum", 0xFF372C49, 850, 2000, 10000, 10));
        TYPES.put("duranite", regType("duranite", 0xFFACDDEB, 1400, 2000, 10000, 10));
        TYPES.put("valyrium", regType("valyrium", 0xFFE85C31, 1915, 2000, 10000, 10));
        TYPES.put("vibranium", regType("vibranium", 0xFFBAD2D9, 3050, 2000, 10000, 10));
        TYPES.put("karmesine", regType("karmesine", 0xFFEB484A, 750, 2000, 9000, 10));
        TYPES.put("jauxum", regType("jauxum", 0xFF68C663, 750, 2000, 9000, 10));
        TYPES.put("ovium", regType("ovium", 0xFF7D77C3, 750, 2000, 9000, 10));
        TYPES.put("terrax", regType("terrax", 0xFFA5978E, 850, 2000, 9000, 10));
        TYPES.put("palladium", regType("palladium", 0xFFEE8736, 690, 2000, 10000, 10));
        TYPES.put("osram", regType("osram", 0xFFFFBC90, 800, 2000, 4000, 10));
        TYPES.put("abyssum", regType("abyssum", 0xFF21BCC2, 700, 2000, 10000, 10));
        TYPES.put("eezo", regType("eezo", 0xFF58798A, 450, 2000, 1000, 0));
        TYPES.put("triberium", regType("triberium", 0xFF66F136, 550, 2000, 9000, 10));
        TYPES.put("fractum", regType("fractum", 0xFFD2C583, 750, 2000, 10000, 10));
        TYPES.put("violium", regType("violium", 0xFFBFB0E2, 850, 2000, 10000, 10));
        TYPES.put("proxii", regType("proxii", 0xFFCEFDE1, 750, 2000, 10000, 10));
        TYPES.put("tritonite", regType("tritonite", 0xFF8EDEFF, 550, 2000, 10000, 10));
        TYPES.put("ignitz", regType("ignitz", 0xFFFF284B, 950, 2000, 6000, 10));
        TYPES.put("imperomite", regType("imperomite", 0xFF7FEFA0, 900, 2000, 10000, 10));
        TYPES.put("solarium", regType("solarium", 0xFFFEF864, 1500, 2000, 2000, 10));
        TYPES.put("nihilite", regType("nihilite", 0xFF6645BA, 580, 2000, 10000, 10));
        TYPES.put("adamant", regType("adamant", 0xFFFF8EFE, 1650, 2000, 10000, 10));
        TYPES.put("dyonite", regType("dyonite", 0xFFFFBD3F, 660, 2000, 7000, 10));
        TYPES.put("nucleum", regType("nucleum", 0xFFE6FF40, 490, 2000, 10000, 10));
        TYPES.put("lumix", regType("lumix", 0xFFF9F3CC, 450, 2000, 8000, 10));
        TYPES.put("seismum", regType("seismum", 0xFFECBCA8, 720, 2000, 10000, 10));
        TYPES.put("astrium", regType("astrium", 0xFF8F385F, 680, 2000, 10000, 10));
        TYPES.put("niob", regType("niob", 0xFF7398B9, 550, 2000, 10000, 10));
        TYPES.put("yrdeen", regType("yrdeen", 0xFF8F385F, 710, 2000, 10000, 10));
        TYPES.put("iox", regType("iox", 0xFF99323C, 900, 2000, 10000, 10));
        TYPES.put("meteorite", regType("meteorite", 0xFF374F3D, 950, 2000, 7000, 10));
        TYPES.put("obsidiorite", regType("obsidiorite", 0xFF224853, 1050, 2000, 7000, 10));
        TYPES.put("magma", regType("magma", 0xFFFFC000, 2000, 2000, 5000, 10));
        TYPES.put("nitronite", regType("nitronite", 0xFFCCFF00, 3100, 2000, 5000, 10));
        TYPES.put("dilithium", regType("dilithium", 0xFF79AEA6, 1500, 2000, 5000, 10));

        SOURCES.put("basalt", FLUIDS.register("molten_basalt",
                () -> new ForgeFlowingFluid.Source(props("basalt"))));
        FLOWINGS.put("basalt", FLUIDS.register("molten_basalt_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("basalt"))));
        SOURCES.put("tiberium", FLUIDS.register("molten_tiberium",
                () -> new ForgeFlowingFluid.Source(props("tiberium"))));
        FLOWINGS.put("tiberium", FLUIDS.register("molten_tiberium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("tiberium"))));
        SOURCES.put("aurorium", FLUIDS.register("molten_aurorium",
                () -> new ForgeFlowingFluid.Source(props("aurorium"))));
        FLOWINGS.put("aurorium", FLUIDS.register("molten_aurorium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("aurorium"))));
        SOURCES.put("prometheum", FLUIDS.register("molten_prometheum",
                () -> new ForgeFlowingFluid.Source(props("prometheum"))));
        FLOWINGS.put("prometheum", FLUIDS.register("molten_prometheum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("prometheum"))));
        SOURCES.put("duranite", FLUIDS.register("molten_duranite",
                () -> new ForgeFlowingFluid.Source(props("duranite"))));
        FLOWINGS.put("duranite", FLUIDS.register("molten_duranite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("duranite"))));
        SOURCES.put("valyrium", FLUIDS.register("molten_valyrium",
                () -> new ForgeFlowingFluid.Source(props("valyrium"))));
        FLOWINGS.put("valyrium", FLUIDS.register("molten_valyrium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("valyrium"))));
        SOURCES.put("vibranium", FLUIDS.register("molten_vibranium",
                () -> new ForgeFlowingFluid.Source(props("vibranium"))));
        FLOWINGS.put("vibranium", FLUIDS.register("molten_vibranium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("vibranium"))));
        SOURCES.put("karmesine", FLUIDS.register("molten_karmesine",
                () -> new ForgeFlowingFluid.Source(props("karmesine"))));
        FLOWINGS.put("karmesine", FLUIDS.register("molten_karmesine_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("karmesine"))));
        SOURCES.put("jauxum", FLUIDS.register("molten_jauxum",
                () -> new ForgeFlowingFluid.Source(props("jauxum"))));
        FLOWINGS.put("jauxum", FLUIDS.register("molten_jauxum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("jauxum"))));
        SOURCES.put("ovium", FLUIDS.register("molten_ovium",
                () -> new ForgeFlowingFluid.Source(props("ovium"))));
        FLOWINGS.put("ovium", FLUIDS.register("molten_ovium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("ovium"))));
        SOURCES.put("terrax", FLUIDS.register("molten_terrax",
                () -> new ForgeFlowingFluid.Source(props("terrax"))));
        FLOWINGS.put("terrax", FLUIDS.register("molten_terrax_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("terrax"))));
        SOURCES.put("palladium", FLUIDS.register("molten_palladium",
                () -> new ForgeFlowingFluid.Source(props("palladium"))));
        FLOWINGS.put("palladium", FLUIDS.register("molten_palladium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("palladium"))));
        SOURCES.put("osram", FLUIDS.register("molten_osram",
                () -> new ForgeFlowingFluid.Source(props("osram"))));
        FLOWINGS.put("osram", FLUIDS.register("molten_osram_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("osram"))));
        SOURCES.put("abyssum", FLUIDS.register("molten_abyssum",
                () -> new ForgeFlowingFluid.Source(props("abyssum"))));
        FLOWINGS.put("abyssum", FLUIDS.register("molten_abyssum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("abyssum"))));
        SOURCES.put("eezo", FLUIDS.register("molten_eezo",
                () -> new ForgeFlowingFluid.Source(props("eezo"))));
        FLOWINGS.put("eezo", FLUIDS.register("molten_eezo_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("eezo"))));
        SOURCES.put("triberium", FLUIDS.register("molten_triberium",
                () -> new ForgeFlowingFluid.Source(props("triberium"))));
        FLOWINGS.put("triberium", FLUIDS.register("molten_triberium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("triberium"))));
        SOURCES.put("fractum", FLUIDS.register("molten_fractum",
                () -> new ForgeFlowingFluid.Source(props("fractum"))));
        FLOWINGS.put("fractum", FLUIDS.register("molten_fractum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("fractum"))));
        SOURCES.put("violium", FLUIDS.register("molten_violium",
                () -> new ForgeFlowingFluid.Source(props("violium"))));
        FLOWINGS.put("violium", FLUIDS.register("molten_violium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("violium"))));
        SOURCES.put("proxii", FLUIDS.register("molten_proxii",
                () -> new ForgeFlowingFluid.Source(props("proxii"))));
        FLOWINGS.put("proxii", FLUIDS.register("molten_proxii_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("proxii"))));
        SOURCES.put("tritonite", FLUIDS.register("molten_tritonite",
                () -> new ForgeFlowingFluid.Source(props("tritonite"))));
        FLOWINGS.put("tritonite", FLUIDS.register("molten_tritonite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("tritonite"))));
        SOURCES.put("ignitz", FLUIDS.register("molten_ignitz",
                () -> new ForgeFlowingFluid.Source(props("ignitz"))));
        FLOWINGS.put("ignitz", FLUIDS.register("molten_ignitz_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("ignitz"))));
        SOURCES.put("imperomite", FLUIDS.register("molten_imperomite",
                () -> new ForgeFlowingFluid.Source(props("imperomite"))));
        FLOWINGS.put("imperomite", FLUIDS.register("molten_imperomite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("imperomite"))));
        SOURCES.put("solarium", FLUIDS.register("molten_solarium",
                () -> new ForgeFlowingFluid.Source(props("solarium"))));
        FLOWINGS.put("solarium", FLUIDS.register("molten_solarium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("solarium"))));
        SOURCES.put("nihilite", FLUIDS.register("molten_nihilite",
                () -> new ForgeFlowingFluid.Source(props("nihilite"))));
        FLOWINGS.put("nihilite", FLUIDS.register("molten_nihilite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("nihilite"))));
        SOURCES.put("adamant", FLUIDS.register("molten_adamant",
                () -> new ForgeFlowingFluid.Source(props("adamant"))));
        FLOWINGS.put("adamant", FLUIDS.register("molten_adamant_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("adamant"))));
        SOURCES.put("dyonite", FLUIDS.register("molten_dyonite",
                () -> new ForgeFlowingFluid.Source(props("dyonite"))));
        FLOWINGS.put("dyonite", FLUIDS.register("molten_dyonite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("dyonite"))));
        SOURCES.put("nucleum", FLUIDS.register("molten_nucleum",
                () -> new ForgeFlowingFluid.Source(props("nucleum"))));
        FLOWINGS.put("nucleum", FLUIDS.register("molten_nucleum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("nucleum"))));
        SOURCES.put("lumix", FLUIDS.register("molten_lumix",
                () -> new ForgeFlowingFluid.Source(props("lumix"))));
        FLOWINGS.put("lumix", FLUIDS.register("molten_lumix_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("lumix"))));
        SOURCES.put("seismum", FLUIDS.register("molten_seismum",
                () -> new ForgeFlowingFluid.Source(props("seismum"))));
        FLOWINGS.put("seismum", FLUIDS.register("molten_seismum_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("seismum"))));
        SOURCES.put("astrium", FLUIDS.register("molten_astrium",
                () -> new ForgeFlowingFluid.Source(props("astrium"))));
        FLOWINGS.put("astrium", FLUIDS.register("molten_astrium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("astrium"))));
        SOURCES.put("niob", FLUIDS.register("molten_niob",
                () -> new ForgeFlowingFluid.Source(props("niob"))));
        FLOWINGS.put("niob", FLUIDS.register("molten_niob_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("niob"))));
        SOURCES.put("yrdeen", FLUIDS.register("molten_yrdeen",
                () -> new ForgeFlowingFluid.Source(props("yrdeen"))));
        FLOWINGS.put("yrdeen", FLUIDS.register("molten_yrdeen_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("yrdeen"))));
        SOURCES.put("iox", FLUIDS.register("molten_iox",
                () -> new ForgeFlowingFluid.Source(props("iox"))));
        FLOWINGS.put("iox", FLUIDS.register("molten_iox_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("iox"))));
        SOURCES.put("meteorite", FLUIDS.register("molten_meteorite",
                () -> new ForgeFlowingFluid.Source(props("meteorite"))));
        FLOWINGS.put("meteorite", FLUIDS.register("molten_meteorite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("meteorite"))));
        SOURCES.put("obsidiorite", FLUIDS.register("molten_obsidiorite",
                () -> new ForgeFlowingFluid.Source(props("obsidiorite"))));
        FLOWINGS.put("obsidiorite", FLUIDS.register("molten_obsidiorite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("obsidiorite"))));
        SOURCES.put("magma", FLUIDS.register("molten_magma",
                () -> new ForgeFlowingFluid.Source(props("magma"))));
        FLOWINGS.put("magma", FLUIDS.register("molten_magma_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("magma"))));
        SOURCES.put("nitronite", FLUIDS.register("molten_nitronite",
                () -> new ForgeFlowingFluid.Source(props("nitronite"))));
        FLOWINGS.put("nitronite", FLUIDS.register("molten_nitronite_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("nitronite"))));
        SOURCES.put("dilithium", FLUIDS.register("molten_dilithium",
                () -> new ForgeFlowingFluid.Source(props("dilithium"))));
        FLOWINGS.put("dilithium", FLUIDS.register("molten_dilithium_flowing",
                () -> new ForgeFlowingFluid.Flowing(props("dilithium"))));
    }

    public static void register(IEventBus modEventBus) {
        FLUID_TYPES.register(modEventBus);
        FLUIDS.register(modEventBus);
    }
}
