// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga;

import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.HashMap;
import java.util.Map;

public final class TaigaItems {

    public static final DeferredRegister<Item> ITEMS =
            DeferredRegister.create(ForgeRegistries.ITEMS, TaigaPlugin.MODID);

    public static final Map<String, RegistryObject<Item>> INGOTS = new HashMap<>();
    public static final Map<String, RegistryObject<Item>> NUGGETS = new HashMap<>();
    public static final Map<String, RegistryObject<Item>> DUSTS = new HashMap<>();
    public static final Map<String, RegistryObject<Item>> CRYSTALS = new HashMap<>();
    public static final Map<String, RegistryObject<Item>> BUCKETS = new HashMap<>();

    private TaigaItems() {}

    static {
        INGOTS.put("abyssum", ITEMS.register("abyssum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("abyssum", ITEMS.register("abyssum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("abyssum", ITEMS.register("abyssum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("adamant", ITEMS.register("adamant_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("adamant", ITEMS.register("adamant_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("adamant", ITEMS.register("adamant_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("astrium", ITEMS.register("astrium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("astrium", ITEMS.register("astrium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("astrium", ITEMS.register("astrium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("aurorium", ITEMS.register("aurorium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("aurorium", ITEMS.register("aurorium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("aurorium", ITEMS.register("aurorium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("basalt", ITEMS.register("basalt_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("basalt", ITEMS.register("basalt_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("basalt", ITEMS.register("basalt_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("dilithium", ITEMS.register("dilithium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("dilithium", ITEMS.register("dilithium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("dilithium", ITEMS.register("dilithium_dust", () -> new Item(new Item.Properties())));
        CRYSTALS.put("dilithium", ITEMS.register("dilithium_crystal", () -> new Item(new Item.Properties())));
        INGOTS.put("duranite", ITEMS.register("duranite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("duranite", ITEMS.register("duranite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("duranite", ITEMS.register("duranite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("dyonite", ITEMS.register("dyonite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("dyonite", ITEMS.register("dyonite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("dyonite", ITEMS.register("dyonite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("eezo", ITEMS.register("eezo_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("eezo", ITEMS.register("eezo_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("eezo", ITEMS.register("eezo_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("fractum", ITEMS.register("fractum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("fractum", ITEMS.register("fractum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("fractum", ITEMS.register("fractum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("ignitz", ITEMS.register("ignitz_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("ignitz", ITEMS.register("ignitz_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("ignitz", ITEMS.register("ignitz_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("imperomite", ITEMS.register("imperomite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("imperomite", ITEMS.register("imperomite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("imperomite", ITEMS.register("imperomite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("iox", ITEMS.register("iox_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("iox", ITEMS.register("iox_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("iox", ITEMS.register("iox_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("jauxum", ITEMS.register("jauxum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("jauxum", ITEMS.register("jauxum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("jauxum", ITEMS.register("jauxum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("karmesine", ITEMS.register("karmesine_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("karmesine", ITEMS.register("karmesine_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("karmesine", ITEMS.register("karmesine_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("lumix", ITEMS.register("lumix_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("lumix", ITEMS.register("lumix_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("lumix", ITEMS.register("lumix_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("meteorite", ITEMS.register("meteorite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("meteorite", ITEMS.register("meteorite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("meteorite", ITEMS.register("meteorite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("nihilite", ITEMS.register("nihilite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("nihilite", ITEMS.register("nihilite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("nihilite", ITEMS.register("nihilite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("niob", ITEMS.register("niob_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("niob", ITEMS.register("niob_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("niob", ITEMS.register("niob_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("nucleum", ITEMS.register("nucleum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("nucleum", ITEMS.register("nucleum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("nucleum", ITEMS.register("nucleum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("obsidiorite", ITEMS.register("obsidiorite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("obsidiorite", ITEMS.register("obsidiorite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("obsidiorite", ITEMS.register("obsidiorite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("osram", ITEMS.register("osram_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("osram", ITEMS.register("osram_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("osram", ITEMS.register("osram_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("ovium", ITEMS.register("ovium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("ovium", ITEMS.register("ovium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("ovium", ITEMS.register("ovium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("palladium", ITEMS.register("palladium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("palladium", ITEMS.register("palladium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("palladium", ITEMS.register("palladium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("prometheum", ITEMS.register("prometheum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("prometheum", ITEMS.register("prometheum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("prometheum", ITEMS.register("prometheum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("proxii", ITEMS.register("proxii_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("proxii", ITEMS.register("proxii_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("proxii", ITEMS.register("proxii_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("seismum", ITEMS.register("seismum_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("seismum", ITEMS.register("seismum_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("seismum", ITEMS.register("seismum_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("solarium", ITEMS.register("solarium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("solarium", ITEMS.register("solarium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("solarium", ITEMS.register("solarium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("terrax", ITEMS.register("terrax_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("terrax", ITEMS.register("terrax_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("terrax", ITEMS.register("terrax_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("tiberium", ITEMS.register("tiberium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("tiberium", ITEMS.register("tiberium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("tiberium", ITEMS.register("tiberium_dust", () -> new Item(new Item.Properties())));
        CRYSTALS.put("tiberium", ITEMS.register("tiberium_crystal", () -> new Item(new Item.Properties())));
        INGOTS.put("triberium", ITEMS.register("triberium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("triberium", ITEMS.register("triberium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("triberium", ITEMS.register("triberium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("tritonite", ITEMS.register("tritonite_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("tritonite", ITEMS.register("tritonite_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("tritonite", ITEMS.register("tritonite_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("valyrium", ITEMS.register("valyrium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("valyrium", ITEMS.register("valyrium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("valyrium", ITEMS.register("valyrium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("vibranium", ITEMS.register("vibranium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("vibranium", ITEMS.register("vibranium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("vibranium", ITEMS.register("vibranium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("violium", ITEMS.register("violium_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("violium", ITEMS.register("violium_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("violium", ITEMS.register("violium_dust", () -> new Item(new Item.Properties())));
        INGOTS.put("yrdeen", ITEMS.register("yrdeen_ingot", () -> new Item(new Item.Properties())));
        NUGGETS.put("yrdeen", ITEMS.register("yrdeen_nugget", () -> new Item(new Item.Properties())));
        DUSTS.put("yrdeen", ITEMS.register("yrdeen_dust", () -> new Item(new Item.Properties())));

        BUCKETS.put("basalt", ITEMS.register("molten_basalt_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("basalt").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("tiberium", ITEMS.register("molten_tiberium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("tiberium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("aurorium", ITEMS.register("molten_aurorium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("aurorium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("prometheum", ITEMS.register("molten_prometheum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("prometheum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("duranite", ITEMS.register("molten_duranite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("duranite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("valyrium", ITEMS.register("molten_valyrium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("valyrium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("vibranium", ITEMS.register("molten_vibranium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("vibranium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("karmesine", ITEMS.register("molten_karmesine_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("karmesine").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("jauxum", ITEMS.register("molten_jauxum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("jauxum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("ovium", ITEMS.register("molten_ovium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("ovium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("terrax", ITEMS.register("molten_terrax_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("terrax").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("palladium", ITEMS.register("molten_palladium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("palladium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("osram", ITEMS.register("molten_osram_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("osram").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("abyssum", ITEMS.register("molten_abyssum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("abyssum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("eezo", ITEMS.register("molten_eezo_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("eezo").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("triberium", ITEMS.register("molten_triberium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("triberium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("fractum", ITEMS.register("molten_fractum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("fractum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("violium", ITEMS.register("molten_violium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("violium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("proxii", ITEMS.register("molten_proxii_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("proxii").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("tritonite", ITEMS.register("molten_tritonite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("tritonite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("ignitz", ITEMS.register("molten_ignitz_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("ignitz").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("imperomite", ITEMS.register("molten_imperomite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("imperomite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("solarium", ITEMS.register("molten_solarium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("solarium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("nihilite", ITEMS.register("molten_nihilite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("nihilite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("adamant", ITEMS.register("molten_adamant_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("adamant").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("dyonite", ITEMS.register("molten_dyonite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("dyonite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("nucleum", ITEMS.register("molten_nucleum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("nucleum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("lumix", ITEMS.register("molten_lumix_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("lumix").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("seismum", ITEMS.register("molten_seismum_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("seismum").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("astrium", ITEMS.register("molten_astrium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("astrium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("niob", ITEMS.register("molten_niob_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("niob").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("yrdeen", ITEMS.register("molten_yrdeen_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("yrdeen").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("iox", ITEMS.register("molten_iox_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("iox").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("meteorite", ITEMS.register("molten_meteorite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("meteorite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("obsidiorite", ITEMS.register("molten_obsidiorite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("obsidiorite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("magma", ITEMS.register("molten_magma_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("magma").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("nitronite", ITEMS.register("molten_nitronite_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("nitronite").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        BUCKETS.put("dilithium", ITEMS.register("molten_dilithium_bucket",
                () -> new BucketItem(() -> TaigaFluids.SOURCES.get("dilithium").get(),
                        new Item.Properties().craftRemainder(Items.BUCKET).stacksTo(1))));
        TaigaBlockItems.registerAll();
    }

    public static void register(IEventBus modEventBus) {
        ITEMS.register(modEventBus);
    }
}
