// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;

/** Registered inside the TaigaItems static block so BlockItems share its DeferredRegister. */
final class TaigaBlockItems {

    private TaigaBlockItems() {}

    static void registerAll() {
        TaigaItems.ITEMS.register("abyssum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("abyssum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("abyssum_ore", () -> new BlockItem(TaigaBlocks.ORES.get("abyssum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("adamant_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("adamant").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("astrium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("astrium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("aurorium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("aurorium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("aurorium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("aurorium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("basalt_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("basalt").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("basalt_ore", () -> new BlockItem(TaigaBlocks.ORES.get("basalt").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("dilithium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("dilithium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("dilithium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("dilithium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("duranite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("duranite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("duranite_ore", () -> new BlockItem(TaigaBlocks.ORES.get("duranite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("dyonite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("dyonite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("eezo_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("eezo").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("eezo_ore", () -> new BlockItem(TaigaBlocks.ORES.get("eezo").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("fractum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("fractum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("ignitz_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("ignitz").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("imperomite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("imperomite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("iox_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("iox").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("jauxum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("jauxum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("jauxum_ore", () -> new BlockItem(TaigaBlocks.ORES.get("jauxum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("karmesine_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("karmesine").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("karmesine_ore", () -> new BlockItem(TaigaBlocks.ORES.get("karmesine").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("lumix_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("lumix").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("meteorite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("meteorite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("nihilite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("nihilite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("niob_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("niob").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("nucleum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("nucleum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("obsidiorite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("obsidiorite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("osram_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("osram").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("osram_ore", () -> new BlockItem(TaigaBlocks.ORES.get("osram").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("ovium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("ovium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("ovium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("ovium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("palladium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("palladium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("palladium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("palladium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("prometheum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("prometheum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("prometheum_ore", () -> new BlockItem(TaigaBlocks.ORES.get("prometheum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("proxii_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("proxii").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("seismum_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("seismum").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("solarium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("solarium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("terrax_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("terrax").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("tiberium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("tiberium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("tiberium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("tiberium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("triberium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("triberium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("tritonite_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("tritonite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("valyrium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("valyrium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("valyrium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("valyrium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("vibranium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("vibranium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("vibranium_ore", () -> new BlockItem(TaigaBlocks.ORES.get("vibranium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("violium_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("violium").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("yrdeen_block", () -> new BlockItem(TaigaBlocks.METAL_BLOCKS.get("yrdeen").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("meteorite_cobble", () -> new BlockItem(TaigaBlocks.COBBLES.get("meteorite").get(), new Item.Properties()));
        TaigaItems.ITEMS.register("obsidiorite_cobble", () -> new BlockItem(TaigaBlocks.COBBLES.get("obsidiorite").get(), new Item.Properties()));
    }
}
