// Generated by D:/tmp/taiga_java_port.py — regenerate, do not hand-edit.
package com.soul.soa_additions.taiga;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.LiquidBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import slimeknights.tconstruct.fluids.block.BurningLiquidBlock;

import java.util.HashMap;
import java.util.Map;

public final class TaigaBlocks {

    public static final DeferredRegister<Block> BLOCKS =
            DeferredRegister.create(ForgeRegistries.BLOCKS, TaigaPlugin.MODID);

    public static final Map<String, RegistryObject<Block>> METAL_BLOCKS = new HashMap<>();
    public static final Map<String, RegistryObject<Block>> ORES = new HashMap<>();
    public static final Map<String, RegistryObject<Block>> COBBLES = new HashMap<>();
    public static final Map<String, RegistryObject<LiquidBlock>> FLUID_BLOCKS = new HashMap<>();

    private TaigaBlocks() {}

    private static BlockBehaviour.Properties metalBlockProps() {
        return BlockBehaviour.Properties.of()
                .mapColor(MapColor.METAL)
                .sound(SoundType.METAL)
                .destroyTime(5.0f)
                .explosionResistance(2000.0f)
                .requiresCorrectToolForDrops();
    }

    private static BlockBehaviour.Properties oreBlockProps() {
        return BlockBehaviour.Properties.of()
                .mapColor(MapColor.STONE)
                .sound(SoundType.STONE)
                .destroyTime(10.0f)
                .explosionResistance(2000.0f)
                .requiresCorrectToolForDrops();
    }

    private static BlockBehaviour.Properties cobbleProps() {
        return BlockBehaviour.Properties.of()
                .mapColor(MapColor.STONE)
                .sound(SoundType.STONE)
                .destroyTime(2.0f)
                .explosionResistance(6.0f)
                .requiresCorrectToolForDrops();
    }

    private static BlockBehaviour.Properties fluidBlockProps() {
        return BlockBehaviour.Properties.of()
                .mapColor(MapColor.FIRE)
                .noCollission()
                .replaceable()
                .strength(100.0f)
                .pushReaction(net.minecraft.world.level.material.PushReaction.DESTROY)
                .noLootTable()
                .liquid();
    }

    static {
        METAL_BLOCKS.put("abyssum", BLOCKS.register("abyssum_block", () -> new Block(metalBlockProps())));
        ORES.put("abyssum", BLOCKS.register("abyssum_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("adamant", BLOCKS.register("adamant_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("astrium", BLOCKS.register("astrium_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("aurorium", BLOCKS.register("aurorium_block", () -> new Block(metalBlockProps())));
        ORES.put("aurorium", BLOCKS.register("aurorium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("basalt", BLOCKS.register("basalt_block", () -> new Block(metalBlockProps())));
        ORES.put("basalt", BLOCKS.register("basalt_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("dilithium", BLOCKS.register("dilithium_block", () -> new Block(metalBlockProps())));
        ORES.put("dilithium", BLOCKS.register("dilithium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("duranite", BLOCKS.register("duranite_block", () -> new Block(metalBlockProps())));
        ORES.put("duranite", BLOCKS.register("duranite_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("dyonite", BLOCKS.register("dyonite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("eezo", BLOCKS.register("eezo_block", () -> new Block(metalBlockProps())));
        ORES.put("eezo", BLOCKS.register("eezo_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("fractum", BLOCKS.register("fractum_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("ignitz", BLOCKS.register("ignitz_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("imperomite", BLOCKS.register("imperomite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("iox", BLOCKS.register("iox_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("jauxum", BLOCKS.register("jauxum_block", () -> new Block(metalBlockProps())));
        ORES.put("jauxum", BLOCKS.register("jauxum_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("karmesine", BLOCKS.register("karmesine_block", () -> new Block(metalBlockProps())));
        ORES.put("karmesine", BLOCKS.register("karmesine_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("lumix", BLOCKS.register("lumix_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("meteorite", BLOCKS.register("meteorite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("nihilite", BLOCKS.register("nihilite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("niob", BLOCKS.register("niob_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("nucleum", BLOCKS.register("nucleum_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("obsidiorite", BLOCKS.register("obsidiorite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("osram", BLOCKS.register("osram_block", () -> new Block(metalBlockProps())));
        ORES.put("osram", BLOCKS.register("osram_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("ovium", BLOCKS.register("ovium_block", () -> new Block(metalBlockProps())));
        ORES.put("ovium", BLOCKS.register("ovium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("palladium", BLOCKS.register("palladium_block", () -> new Block(metalBlockProps())));
        ORES.put("palladium", BLOCKS.register("palladium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("prometheum", BLOCKS.register("prometheum_block", () -> new Block(metalBlockProps())));
        ORES.put("prometheum", BLOCKS.register("prometheum_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("proxii", BLOCKS.register("proxii_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("seismum", BLOCKS.register("seismum_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("solarium", BLOCKS.register("solarium_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("terrax", BLOCKS.register("terrax_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("tiberium", BLOCKS.register("tiberium_block", () -> new Block(metalBlockProps())));
        ORES.put("tiberium", BLOCKS.register("tiberium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("triberium", BLOCKS.register("triberium_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("tritonite", BLOCKS.register("tritonite_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("valyrium", BLOCKS.register("valyrium_block", () -> new Block(metalBlockProps())));
        ORES.put("valyrium", BLOCKS.register("valyrium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("vibranium", BLOCKS.register("vibranium_block", () -> new Block(metalBlockProps())));
        ORES.put("vibranium", BLOCKS.register("vibranium_ore", () -> new Block(oreBlockProps())));
        METAL_BLOCKS.put("violium", BLOCKS.register("violium_block", () -> new Block(metalBlockProps())));
        METAL_BLOCKS.put("yrdeen", BLOCKS.register("yrdeen_block", () -> new Block(metalBlockProps())));
        COBBLES.put("meteorite", BLOCKS.register("meteorite_cobble", () -> new Block(cobbleProps())));
        COBBLES.put("obsidiorite", BLOCKS.register("obsidiorite_cobble", () -> new Block(cobbleProps())));

        FLUID_BLOCKS.put("basalt", BLOCKS.register("molten_basalt_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("basalt").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("tiberium", BLOCKS.register("molten_tiberium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("tiberium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("aurorium", BLOCKS.register("molten_aurorium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("aurorium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("prometheum", BLOCKS.register("molten_prometheum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("prometheum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("duranite", BLOCKS.register("molten_duranite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("duranite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("valyrium", BLOCKS.register("molten_valyrium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("valyrium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("vibranium", BLOCKS.register("molten_vibranium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("vibranium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("karmesine", BLOCKS.register("molten_karmesine_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("karmesine").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("jauxum", BLOCKS.register("molten_jauxum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("jauxum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("ovium", BLOCKS.register("molten_ovium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("ovium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("terrax", BLOCKS.register("molten_terrax_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("terrax").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("palladium", BLOCKS.register("molten_palladium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("palladium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("osram", BLOCKS.register("molten_osram_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("osram").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("abyssum", BLOCKS.register("molten_abyssum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("abyssum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("eezo", BLOCKS.register("molten_eezo_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("eezo").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("triberium", BLOCKS.register("molten_triberium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("triberium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("fractum", BLOCKS.register("molten_fractum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("fractum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("violium", BLOCKS.register("molten_violium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("violium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("proxii", BLOCKS.register("molten_proxii_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("proxii").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("tritonite", BLOCKS.register("molten_tritonite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("tritonite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("ignitz", BLOCKS.register("molten_ignitz_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("ignitz").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("imperomite", BLOCKS.register("molten_imperomite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("imperomite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("solarium", BLOCKS.register("molten_solarium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("solarium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("nihilite", BLOCKS.register("molten_nihilite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("nihilite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("adamant", BLOCKS.register("molten_adamant_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("adamant").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("dyonite", BLOCKS.register("molten_dyonite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("dyonite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("nucleum", BLOCKS.register("molten_nucleum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("nucleum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("lumix", BLOCKS.register("molten_lumix_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("lumix").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("seismum", BLOCKS.register("molten_seismum_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("seismum").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("astrium", BLOCKS.register("molten_astrium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("astrium").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("niob", BLOCKS.register("molten_niob_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("niob").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("yrdeen", BLOCKS.register("molten_yrdeen_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("yrdeen").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("iox", BLOCKS.register("molten_iox_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("iox").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("meteorite", BLOCKS.register("molten_meteorite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("meteorite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("obsidiorite", BLOCKS.register("molten_obsidiorite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("obsidiorite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("magma", BLOCKS.register("molten_magma_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("magma").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("nitronite", BLOCKS.register("molten_nitronite_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("nitronite").get(),
                        fluidBlockProps(), 10, 4.0f)));
        FLUID_BLOCKS.put("dilithium", BLOCKS.register("molten_dilithium_block",
                () -> new BurningLiquidBlock(() -> TaigaFluids.SOURCES.get("dilithium").get(),
                        fluidBlockProps(), 10, 4.0f)));
    }

    public static void register(IEventBus modEventBus) {
        BLOCKS.register(modEventBus);
    }
}
